name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**" # Only trigger on changes to the terraform directory

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6 # Specify the Terraform version

      # Step 3: Initialize Terraform
      - name: Terraform Init
        working-directory: ./terraform # Specify the directory where your Terraform files are located
        run: terraform init

      # Step 4: Terraform Plan (Optional, for debugging)
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      # Step 5: Terraform Apply
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
