on:
  workflow_call: # This makes it reusable

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout the repository
      - name: Debug AWS_REGION
        run: |
          echo "AWS_REGION is: ${{ secrets.AWS_REGION }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      # Step 3: Initialize Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 4: Terraform Plan (Optional, for debugging)
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      # Step 5: Terraform Apply
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
