name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**" # Only trigger on changes to the terraform directory

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      # Step 3: Initialize Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 4: Terraform Plan (Optional, for debugging)
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      # Step 5: Terraform Apply
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
